### ISSUE TITLE
播放器默认播放为静音，如何解决？

### ISSUE THREAD

**Issue by yangchangming** [pansyjs/react-components#115]
加载视频成功后，默认为静音状态，如何进行设置？谢谢！
我用的版本是1.3.0
配置如下：

`<Player
      source={currentPlayUrl}
      ref={playerRef}
      options={{
          autoplay: true,
          height: '500px',
          preload: true,
          isLive: false
      }}
  />`

**Comment by wangxingkang** [comment]
ref.setVolume(0.5)

**Comment by wangxingkang** [comment]
要不升级下版本吧 新版本就是 ref 引用变动 其他都没变化

**Comment by yangchangming** [comment]
谢谢回答！
升级到最新版，但是报另外一个错误，就是类型错误什么的，我看了一下vue版本有类似的错误，好像是说外层div id的什么问题，我没有解决！

**Comment by yangchangming** [comment]
报错信息如下！
Uncaught TypeError: 没有为播放器指定容器

**Comment by wangxingkang** [comment]
提供个最小复现吧

**Comment by hanwenbo** [comment]
@wangxingkang 用ref设置声音 在pc的web下会暂停，可能实例的时机不对

**Comment by wangxingkang** [comment]
@yangchangming  @pansy/react-aliplayer: 2.1.0 => 2.1.1
