### ISSUE TITLE
@pansy/react-aliplayer 的onXxxx事件无法触发

### ISSUE THREAD

**Issue by hanwenbo** [pansyjs/react-components#118]
<img width="175" alt="image" src="https://user-images.githubusercontent.com/5869741/222099551-786f7505-76fb-41c3-b1d2-e561ac41dedc.png">

暂停、播放等是一样的 没被触发

**Comment by wangxingkang** [comment]
https://github.com/pansyjs/react-components/commit/d7c01126d8964dd851d0ca11ce12c9790080569a

**Comment by wangxingkang** [comment]
已修复
