### ISSUE TITLE
vlc、potplayer能播放的视频提示解码错误，怎么解决？

### ISSUE THREAD

**Issue by fengnex** [pansyjs/react-components#19]
![image](https://user-images.githubusercontent.com/26297547/101463779-d1951800-3978-11eb-8866-3228d041fe71.png)
如上图suo所示，相关的视频用vlc、potplayer都能正常播放，验证的格式包括mkv、mp4，但是@pansy/react-aliplayer提示“解码错误”，如上图所示，请问怎么解决？

**Comment by wangxingkang** [comment]
这个封装的阿里的播放器，可以在 http://player.alicdn.com/aliplayer/setting/setting.html 试一试是否播放正常。

**Comment by fengnex** [comment]
请问怎么更新播放器的解码器？
如果需要通过这个来支持播放更多水平的话。

**Comment by wangxingkang** [comment]
这个就不知道了 阿里的播放器不是开源的，具体请看阿里播放器文档 这里只是做了封装

**Comment by wangxingkang** [comment]
暂时先关了，有与阿里播放器不一致的情况请反馈
