### ISSUE TITLE
高德地图封装

### ISSUE THREAD

**Issue by wangxingkang** [pansyjs/react-components#2]
## 基础组件
- [x] Map地图组件
    - [x] 相关示例完善  [wangxingkang](https://github.com/wangxingkang)
      请参考 https://elemefe.github.io/react-amap/components/map (除Map 中 plugins 的使用示例外)
    - [x] 自定义地图组件文档书写
    - [x] API文档书写 
- [x] MouseTool 组件  [wangxingkang](https://github.com/wangxingkang)
    - [x] 相关示例完善
    - [x] API文档书写 

## 覆盖物

https://lbs.amap.com/api/javascript-api/reference/overlay

- [x] Marker 标记点 [wangxingkang](https://github.com/wangxingkang)
    - [x] 相关示例完善
    - [ ] API文档书写 
- [x] Markers 多标记点组件 [wangxingkang](https://github.com/wangxingkang)
    - [ ] 相关示例完善
    - [ ] API文档书写 
- [ ] Text 文本标注
    - [ ] 相关示例完善
    - [ ] API文档书写 
- [ ] BezierCurve 组件
    - [ ] 相关示例完善
    - [ ] API文档书写 
- [x] Polygon 多边形 [phobal](https://github.com/phobal)
    - [x] 相关示例完善
    - [x] API文档书写 
- [ ] PolyLine 折线组件 [phobal](https://github.com/phobal)
    - [ ] 相关示例完善
    - [ ] API文档书写 
- [x] Circle 圆形组件 [phobal](https://github.com/phobal)
    - [ ] 相关示例完善
    - [ ] API文档书写 
- [ ] Ellipse 组件 [phobal](https://github.com/phobal)
    - [ ] 相关示例完善
    - [ ] API文档书写 
- [ ] ContextMenu 组件
    - [ ] 相关示例完善
    - [ ] API文档书写 
- [x] Rectangle 矩形组件 [phobal](https://github.com/phobal)
    - [ ] 相关示例完善
    - [ ] API文档书写 

## 信息窗体

https://lbs.amap.com/api/javascript-api/reference/infowindow

- [x] InfoWindow 组件
    - [ ] 相关示例完善
    - [ ] API文档书写 

## 搜索服务

https://lbs.amap.com/api/javascript-api/reference/search

- [x] Autocomplete 组件
    - [ ] 相关示例完善
    - [ ] API文档书写 

## 地图控件封装

https://lbs.amap.com/api/javascript-api/reference/map-control

- [x] ControlBar 组件
    - [x] 相关示例完善
    - [x] API文档书写 
- [x] MapType 组件
    - [x] 相关示例完善
    - [x] API文档书写 
- [x] OverView 组件
    - [x] 相关示例完善
    - [x] API文档书写 
- [x] Scale  组件
    - [x] 相关示例完善
    - [x] API文档书写 
- [x] ToolBar  组件
    - [x] 相关示例完善
    - [x] API文档书写

**Comment by wangxingkang** [comment]
开发分支: feat/amap

**Comment by wangxingkang** [comment]
欢迎反馈和PR

**Comment by wangxingkang** [comment]
Test

**Comment by phobal** [comment]
## 图层

https://lbs.amap.com/api/javascript-api/guide/layers/official-layers

- [ ] 官方图层(标准、卫星、路网、实时交通、建筑楼块、室内、3D 图层)
    - [ ] 相关示例完善
    - [ ] API 文档书写
- [ ] 第三方图层(WMS、WMTS、XYZ 切片图层 )
    - [ ] 相关示例完善
    - [ ] API 文档书写
- [ ] 自有数据展示图层(图片、视频、Canvas、任意切片、完全自定义、热力图、GeoJSON 图层)
    - [ ] 相关示例完善
    - [ ] API 文档书写

**Comment by wangxingkang** [comment]
@phobal 你这个就自己开发吧，等着你的PR

**Comment by phobal** [comment]
> @phobal 你这个就自己开发吧，等着你的PR

OK 🙆‍♂️

**Comment by wangxingkang** [comment]
在 https://github.com/pansyjs/react-amap 维护
