### ISSUE TITLE
水印很容易被删除

### ISSUE THREAD

**Issue by lzecheng** [pansyjs/react-components#23]
1.整个div删除，水印就没了。
2.先删属性data-1，再删style，水印也没了

**Comment by wangxingkang** [comment]
你说的是挂载节点吗？

**Comment by lzecheng** [comment]
data-1那个层级是不能删除，但是可以直接删除它的父div

**Comment by wangxingkang** [comment]
https://github.com/pansyjs/watermark/commit/915fd03f967da6061346673b1619fe2bd1b4a6e5 已修复

**Comment by wangxingkang** [comment]
试一下 需要 pansyjs/watermark v1.4.0

**Comment by wangxingkang** [comment]
@lzecheng 问题解决了吗？

**Comment by wangxingkang** [comment]
先关闭了，有问题再开新的
