### ISSUE TITLE
【react-amap】useSetProperties 自定义 hook 问题

### ISSUE THREAD

**Issue by phobal** [pansyjs/react-components#7]
### 问题
运行文档后进入：components/amap-overlay/marker， 报如下错误：

![image](https://user-images.githubusercontent.com/9244211/96358735-28326280-113d-11eb-91b5-1dd766a4fd73.png)

### debug
debug 后查看源代码中：
![image](https://user-images.githubusercontent.com/9244211/96358700-b0643800-113c-11eb-8234-119858005943.png)
map 对象存在循环引用的对象，而 JSON.stringify 方法的参数不能接受循环引用的对象，不然转换会失败。

### 解决方案探讨

在传给 useSetProperties hook 时去除 map 和 AMap 对象， 这样可以解决这个问题。

但是这样会存在一个问题，有些组件(比如 [Marker](https://lbs.amap.com/api/jsapi-v2/documentation#markersetmap))有 setMap 方法，就会和整个地图的 map 实例同名了，也就是没办法使用 setMap 这个方法了。

题外话：react hook 不建议放在循环嵌套和条件语句中的，这里的代码把 useEffect 放在循环里面了。

**Comment by wangxingkang** [comment]
BUG 已修复

**Comment by wangxingkang** [comment]
暂时想不到好的解决方案，先关闭
